services:
  php:
    image: tugboatqa/php:7-apache
    default: true
    depends: mysql
    
    commands:
      init:    
        - composer --no-ansi global require drush/drush:8.x
        - ln -sf ~/.composer/vendor/bin/drush /usr/local/bin/drush
        
        - mkdir -p ~/.drush/commands
        - cd ~/.drush/commands
        - wget https://github.com/backdrop-contrib/drush/archive/1.x-0.x.zip
        - unzip 1.x-0.x.zip -d backdrop
        - drush cc -y
        
        - drush dlb backdrop
        - ln -snf "${TUGBOAT_ROOT}/backdrop" "${DOCROOT}"
        
        - drush si --db-url="mysql://tugboat:tugboat@mysql/tugboat" -y 
    
  mysql:
    image: tugboatqa/mysql:5
