services:
  php:
    image: tugboatqa/php:7-apache
    default: true
    depends: mysql
    
    commands:
      init:    
        - a2enmod headers rewrite
        
        - composer --no-ansi global require drush/drush:8.x
        - ln -sf ~/.composer/vendor/bin/drush /usr/local/bin/drush
        
        - mkdir -p ~/.drush/commands/ 
        - cd ~/.drush/commands/ && wget https://github.com/backdrop-contrib/drush/archive/1.x-0.x.zip
        - cd ~/.drush/commands/ && unzip 1.x-0.x.zip -d backdrop
        
        - drush dlb backdrop
        - ln -snf "${TUGBOAT_ROOT}/backdrop" "${DOCROOT}"
        
        - drush -r "${DOCROOT}" si --db-url="mysql://tugboat:tugboat@mysql/tugboat" --account-pass="${ADMIN_PWD}" -y 
        
        - mkdir -p "${DOCROOT}/sites/default/files"
        - chown www-data "${DOCROOT}/sites/default/files"
        - chmod 744 "${DOCROOT}/sites/default/files"
              
      build:
        - drush -r "${DOCROOT}" cache-clear all
        - drush -r "${DOCROOT}" updb -y
    
  mysql:
    image: tugboatqa/mysql:5
